learning_templates/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

#for template tagging
app_name = 'basic_app' #must equal app name

urlpatterns = [
    url(r'^relative/$', views.relative, name='relative'),
    url(r'^other/$', views.other, name='other'),
]

learning_templates/learning_templates/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from basic_app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^basic_app/', include('basic_app.urls')),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'hello world!', 'number':100}
    return render(request, 'basic_app/index.html', context_dict)

def other(request):
    return render(request, 'basic_app/other.html')

def relative(request):
    return render(request, 'basic_app/relative_url_templates.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <title></title>
    </head>
    <body>
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <ul class="nav navbar-nav">
                    <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
                    <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                    <li><a class="navbar-link" href="{% url 'basic_app:other' %}">Other</a></li>
                    <li><a class="navbar-link" href="{% url 'basic_app:relative' %}">Relative</a></li>
                </ul>
            </div>
        </nav>
        <div class="container">
            {% block body_block %}
            <!-- Anything outside of this will be inherited when you extend base.html -->
            {% endblock %}
        </div>
    </body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
    {% load my_extras %}
    {% block body_block %}
        <h1>Welcome to INDEX</h1>
        <!-- FILTERS: -->
        <!-- built in -->
        <!-- change to uppercase -->
        <h2>{{ text | upper }}</h2>
        <!-- add number -->
        <h2>{{ number | add:'99' }}</h2>
        <!-- custom -->
        <h2>{{ text | my_cut:' ' }}</h2>
    {% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
    {% block body_block %}
        <h1>Welcome to OTHER</h1>
        <p>This is an example of template inheritance</p>
        <a href="{% url 'basic_app:relative' %}">THE RELATIVE URLS PAGE</a>
    {% endblock %}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
    {% block body_block %}
        <h1>Welcome to RELATIVE URL TEMPLATES</h1>
        <a href="{% url 'basic_app:other' %}">THE OTHER PAGE</a>
        <br>
        <a href="{% url 'admin:index' %}">THE ADMIN PAGE</a>
        <br>
        <a href="{% url 'index' %}">THE HOME PAGE</a>
    {% endblock %}